#! /bin/sh

g++ -fdiagnostics-color=always -fPIC -DUSE_MALLOC_LOCK=1 -pipe -O3 -finline-limit=65000 -fkeep-inline-functions -finline-functions -ffast-math -fomit-frame-pointer -DNDEBUG  -I. -I../../heaplayers -D_REENTRANT=1 -shared libdlmalloc.cpp dlmalloc.c -o libdlmalloc.so

